version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 5432:5432

  node:
    build:
      context: .
    container_name: node
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PGHOST: db
    depends_on:
      - db
    ports:
      - 9090:9090

networks:
  default:
    name: york-inquirer

volumes:
  db-data:
