name: Heroku

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 12
        postgresql db: york_inquirer_test
        postgresql user: test
        postgresql password: test

    - name: Install dependencies 
      run: npm ci

    - name: Run tests
      run: npm test
      env: 
        DB_USER: 'test'
        DB_PASSWORD: 'test'

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        fetch-depth: "0"

    - name: Add heroku remote
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: Deploy to Heroku
      run: git push heroku master
      